# Generated by Django 4.0.1 on 2022-01-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='death_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
